apiVersion: v1
entries:
  guillotina-cms:
  - created: "2019-07-31T14:25:15.82055+02:00"
    description: Guillotina CMS
    digest: f690239a1acfc0faf4801b5c714a6fbe691f8cda0bf33763b719685494a9e4a3
    icon: https://avatars0.githubusercontent.com/u/72034?s=200&v=4
    maintainers:
    - email: ramon@plone.org
      name: Ramon Navarro
    name: guillotina-cms
    sources:
    - https://github.com/plone/guillotina_cms
    urls:
    - https://guillotina.io/charts/guillotina-cms-0.0.1.tgz
    version: 0.0.1
generated: "2019-07-31T14:25:15.81837+02:00"
